### ISSUE TITLE
Puppet 4 upgrade testing failure at postfix/manifests/hash.pp:39:3

### ISSUE THREAD

**Issue by StL-Jim** [camptocamp/puppet-postfix#221]
Using the Puppet preview tool for out migration from Puppet 3 to Puppet 4  I'm getting an error at postfix/manifests/hash.pp:39:3
ERROR: Evaluation Error: Error while evaluating a Function Call, assert_type(): Expected type Stdlib::Absolutepath does not match actual: String

Here's how I have postfix configured
```puppet
class { 'postfix':
  inet_interfaces     => 'localhost',
  inet_protocols      => 'ipv4',
  mta                 => true,
  relayhost           => 'our.relay.host',
  root_mail_recipient => 'email_fwd@address',
}
postfix::config {
  'smtp_use_tls': value   => 'no';
}
```

Any suggestions would be greatly appreciated.

**Comment by centric-jim** [comment]
I've narrowed down the configuration value which causes the error to 
mta => true,

I've tried
mta => True,
which generated this error: Error 400 on SERVER: Expected parameter 'mta' of 'Class[Postfix]' to have type Boolean, got Type[True['']]

I've also tried
mta => 'true'
which generated this error: Expected parameter 'mta' of 'Class[Postfix]' to have type Boolean, got String

I've also tried using satellite instead of mta and get the same error as when I initially opened the tickete
satellite           => true,
Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, assert_type(): Expected type Stdlib::Absolutepath does not match actual: String at /etc/puppet/environments/upgrade/modules/postfix/manifests/hash.pp:39:3


The more I look at the man pages for postconf and postconf (5), I'm getting the idea that mta and satellite really aren't serving a purpose (at least for our Postfix configuration needs).  That instead relayhost (next-hop) is all that's needed.

**Comment by centric-jim** [comment]
With further testing of other nodes, I'm using another hash for a whitelist and I can't seem to work around this one:
postfix::config { 'transport_maps':
    ensure => present,
    value  => 'hash:/etc/postfix/whitelist',
}
postfix::hash {'/etc/postfix/whitelist':
    ensure  => present,
    content => template('postfix/whitelist-dev.erb'),
}

ERROR: Evaluation Error: Error while evaluating a Function Call, assert_type(): Expected type Stdlib::Absolutepath does not match actual: String at /etc/puppet/environments/upgrade/modules/postfix/manifests/hash.pp:39:3

**Comment by raphink** [comment]
Which version of Puppet and which version of the module are you using?

**Comment by StL-Jim** [comment]
I'm so sorry for the slow response.  I'm finally circling back to this issue
Puppet version is 3.8.7
Puppetserver 1.2.0
StdLib version is 4.26.0
Postfix module version is 1.6.0
I'm testing the future parser to upgrade to Puppet 4.x

I don't have any issues with StdLib 4.6.0 (yes I know _very_ old).

**Comment by StL-Jim** [comment]
I have narrowed down the errors:
1. If I have in class Postfilx a value of 'mta => true,' 
The error gets generated
Error: Evaluation Error: Error while evaluating a Function Call, assert_type(): Expected type Stdlib::Absolutepath does not match actual: String at /etc/puppet/environments/upgrade/modules/postfix/manifests/hash.pp:35:3 on node <my_node_fqdn>

I get the same error if I set 'satellite => true,' as well

2. If I define a custom hashmap
# This does not generate and error
postfix::config {
  'relay_recipient_maps': value => 'hash:/etc/postfix/relay_recipients';
}
# This generates an error
postfix::hash {'/etc/postfix/relay_recipients':
  ensure  => present,
  content => template('postfix/whitelist-dev.erb'),
}

What I'm wanting to do, maybe I'm not going about it in the right way, is use relay_recipient_maps to only allow a specific group of recipient email addresses (whitelist) and deny all other
----------from main.cf ---------------------
main.cf:# The relay_recipient_maps parameter specifies optional lookup tables
main.cf:#relay_recipient_maps = hash:/etc/postfix/relay_recipients
--------------------------------------------------------

**Comment by StL-Jim** [comment]
Final note, if I revert back to v1.4.0 of hash.pp (everything else v1.7.0).  I don't get any errors.

**Comment by raphink** [comment]
Setting `mta` to true includes the `postfix::mta` class, which sets up `postfix::hash { '/etc/postfix/virtual': }` and `postfix::hash { '/etc/postfix/transport': }` resources.

It seems the `assert_type()` call in `manifests/hash.pp` does not behave the same in Puppet 3 (with `parser=future`) and in Puppet 4/5/6. I'm not extremely surprised by this, as `parser=future` was not exactly a final implementation imo.

As a note, Puppet 3 has reached its end-of-life 2 years ago, and Puppet 4 was deprecated last month. For that reason, we cannot accept patches for Puppet 3 compatibility in this module.
